version: '3'
services:
  eurekaserver:
    image: 'saichandvemuri/eurekaserver:latest'
    container_name: eurekaserver
    ports:
      - '8761:8761'
  configserver:
    image: 'saichandvemuri/configserver:latest'
    container_name: configserver
    environment:
      - EUREKA_SERVER_ADDRESS=http://eurekaserver:8761/eureka
    healthcheck:
      test: ['CMD',"curl","-f","http://configserver:9296/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - eurekaserver
    ports:
      - '9296:9296'
  cloudgateway:
    image: 'saichandvemuri/cloudgateway:latest'
    container_name: cloudgateway
    environment:
      - EUREKA_SERVER_ADDRESS=http://eurekaserver:8761/eureka
      - CONFIG_SERVER_URL=configserver
    depends_on:
      configserver:
        condition: service_healthy
    ports:
      - '9090:9090'
  security:
    image: 'saichandvemuri/security:latest'
    container_name: security
    environment:
      - EUREKA_SERVER_ADDRESS=http://eurekaserver:8761/eureka
      - CONFIG_SERVER_URL=configserver
    depends_on:
      configserver:
        condition: service_healthy
    ports:
      - '8082:8082'
  library:
    image: 'saichandvemuri/libraryservice:latest'
    container_name: libraryservice
    environment:
      - EUREKA_SERVER_ADDRESS=http://eurekaserver:8761/eureka
      - CONFIG_SERVER_URL=configserver
    depends_on:
      configserver:
        condition: service_healthy
    ports:
      - '8080:8080'