version: '3'
services:
    eurekaserver:
        image: 'saichandvemuri/eurekaserver:latest'
        container_name: eurekaserver
        ports:
          - '8761:8761'
    configserver:
        image: 'saichandvemuri/configserver:latest'
        container_name: configserver
        ports:
          - '9296:9296'
        environment:
            - EUREKA_SERVER_ADDRESS=http://eurekaserver:8761/eureka
        healthcheck:
            test: ["CMD", "curl" ,"-f", "http://configserver:9296/actuator/health"]
            interval: 30s
            timeout: 5s
            retries: 5
            start_period: 30s
        depends_on:
            - eurekaserver
    apigateway:
        image: 'saichandvemuri/apigateway:latest'
        container_name: apigateway
        ports:
          - '9090:9090'
        environment:
            - EUREKA_SERVER_ADDRESS=http://eurekaserver:8761/eureka
            - CONFIG_SERVER_URL=http://configserver:9296
        depends_on:
            configserver:
                condition: service_healthy
  