apiVersion: apps/v1
kind: Deployment
metadata:
  name: security
spec:
  selector:
    matchLabels:
      app: security
  template:
    metadata:
      labels:
        app: security
    spec:
      containers:
      - name: security
        image: saichandvemuri/authsecurity
        ports:
        - containerPort: 8082
        env:
        - name: EUREKA_SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: eureka_service_address
              name: eureka-cm
        - name: CONFIG_SERVER_URL
          valueFrom:
            configMapKeyRef:
              key: config_url
              name: config-cm
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              key: hostname
              name: mysql-cm

---

apiVersion: v1
kind: Service
metadata:
  name: security-svc
spec:
  selector:
    app: security-app
  ports:
  - port: 80
    targetPort: 8082
