server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/news_letter
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  application:
    name: PATIENT-SERVICE
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:9296}
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
logging:
  level:
    root: info